### ISSUE TITLE
The bot do not login on facebook

### ISSUE THREAD

**Issue by RobCraftNet** [Bjornskjald/miscord#105]
## Expected Behavior
![78787](https://user-images.githubusercontent.com/24510243/37444299-25142a76-27e7-11e8-8078-573d986a1011.PNG)

the bot do not log in so get an error 

## Actual Behavior
> messenger-discord@2.5.2 start C:\Users\robbi\Desktop\miscord-master
> node index.js

ERR! login Error retrieving userID. This can be caused by a lot of things, including getting blocked by Facebook for logging in from an unknown location. Try logging in with a browser to verify.
Error:
{ error: 'Error retrieving userID. This can be caused by a lot of things, including getting blocked by Facebook for logging in from an unknown location. Try logging in with a browser to verify.' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! messenger-discord@2.5.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the messenger-discord@2.5.2 start script.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Platform: windows
  - Version (can be found in package.json): 2.5.2
  - Node.js version (`node -v`): 9.5.0

**Comment by Bjornskjald** [comment]
You have literally written on your screenshot:
```
Try logging in with a browser to verify.
```

Have you considered doing that?
Also, what is your main language?

**Comment by RobCraftNet** [comment]
no do change the the bot inex.js yea ve do at to me all day

**Comment by RobCraftNet** [comment]
look to me say the error so be other github put all in code yea

**Comment by RobCraftNet** [comment]
@Bjornskjald ok I download it for and i get the bot get the back work
