### ISSUE TITLE
[Support] Incorrect login details were provided **SOLVED**

### ISSUE THREAD

**Issue by smileydog** [Bjornskjald/miscord#106]
## Expected Behavior
`npm start` would execute as expected.

## Actual Behavior

I am getting an `Incorrect login details were provided` error after running `npm start`. I verified my Facebook login by copying and pasting email and password from the json into the brower and was able to log in. I also tried cycling the Discord bot token several times just in case. Reinstalling git and node didn't help. Deleting and re-cloning another instance of miscord didn't help.

I'm hoping you can help me identify the silly thing I'm missing since plenty of people have your project up and running quite well.

```
C:\Users\me\pgo>git clone https://www.github.com/Bjornskjald/miscord
Cloning into 'miscord'...
warning: redirecting to https://github.com/Bjornskjald/miscord.git/
remote: Counting objects: 759, done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 759 (delta 65), reused 77 (delta 31), pack-reused 636
Receiving objects: 100% (759/759), 605.65 KiB | 12.89 MiB/s, done.
Resolving deltas: 100% (415/415), done.

C:\Users\me\pgo>cd miscord

C:\Users\me\pgo\miscord>copy config.example.json config.json
        1 file(s) copied.

C:\Users\me\pgo\miscord>npm install
added 102 packages from 87 contributors in 6.708s

C:\Users\me\pgo\miscord>npm start

> messenger-discord@2.5.2 start C:\Users\me\pgo\miscord
> node index.js

Error:
Error: Incorrect login details were provided.
    at WebSocketConnection.client.ws.connection.once.event (C:\Users\me\pgo\miscord\node_modules\discord.js\src\client\ClientManager.js:47:41)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at WebSocketConnection.emit (events.js:211:7)
    at WebSocketConnection.onClose (C:\Users\me\pgo\miscord\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:387:10)
    at WebSocket.onClose (C:\Users\me\pgo\miscord\node_modules\ws\lib\event-target.js:124:16)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.emitClose (C:\Users\me\pgo\miscord\node_modules\ws\lib\websocket.js:219:10)
    at _receiver.cleanup (C:\Users\me\pgo\miscord\node_modules\ws\lib\websocket.js:207:39)
    at Receiver.cleanup (C:\Users\me\pgo\miscord\node_modules\ws\lib\receiver.js:572:15)
    at WebSocket.finalize (C:\Users\me\pgo\miscord\node_modules\ws\lib\websocket.js:207:20)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! messenger-discord@2.5.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the messenger-discord@2.5.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2018-03-15T15_25_29_118Z-debug.log
```
## Steps to Reproduce the Problem

  1. Verified that Facebook username and password was correct by copying/pasting credentials into Facebook via web browser. Verified that Facebook user was part of an existing Facebook Messenger group.
  2. Uninstalled both git and node. Restarted Win10. Installed git and node. Restarted.
  3. Cloned miscord instance
  4. Via cmd, `copy config.example.json config.json`
  5. Using Notepad++, filled `config.json` with Facebook email, Facebook password, and discord token with bot Client Secret
  7. ran `npm install`
  7. ran `npm start`

## Specifications

  - Platform: Windows 10 build 1709
  - Version (can be found in package.json): 2.5.2
  - Node.js version (`node -v`): 8.10.0

**Comment by Bjornskjald** [comment]
Can you post an image with blacked out info? it's possible that you have entered your info in a wrong format

**Comment by smileydog** [comment]
![miscord login error](https://user-images.githubusercontent.com/37412093/37475650-91ad827e-2849-11e8-9a81-18394a050f04.PNG)

**Comment by smileydog** [comment]
The JSON format appears to be valid, according to https://jsonlint.com.

**Comment by Bjornskjald** [comment]
wait, it's a discord error. can you check the token if it's correct?

**Comment by smileydog** [comment]
I cycled the bot token again:

![miscord discord bot](https://user-images.githubusercontent.com/37412093/37476450-93d9ecde-284b-11e8-82c6-85c4f4a4be8d.PNG)

Ran `npm install` just in case, then `npm start`. Still got the incorrect login.

**Comment by Bjornskjald** [comment]
i think you're getting the wrong string as token. it should literally say "token" on the discord page

**Comment by smileydog** [comment]
Sunuva ... that was it.  Thanks!

```
C:\Users\me\pgo\miscord>npm start

> messenger-discord@2.5.2 start C:\Users\me\pgo\miscord
> node index.js

info login Logging in...
info login Logged in
info login Request to reconnect
info login Request to pull 1
info login Request to pull 2
info login Request to thread_sync
info login Done logging in.
info listen Got answer in 1042
info listen Got answer in 582
```

**Comment by smileydog** [comment]
@Bjornskjald Thank you again. Feel free to close this ticket (or you can leave it up just in case someone else runs into the same issue.)
