### ISSUE TITLE
Add username to Discord notifications

### ISSUE THREAD

**Issue by smileydog** [Bjornskjald/miscord#107]
Both desktop and mobile Discord notifications for incoming bridged Messenger messages show the bot name, but not the Facebook user who sent the original message. Is it possible for Miscord to display the user name in Discord notifications? Thanks!

**Comment by Bjornskjald** [comment]
I don't think this would be possible due to the way Discord shows embeds in notifications

**Comment by Bjornskjald** [comment]
Checked, works but it would need adding an username to the original message and editing it after sending to remove that username which can be pretty annoying.

**Comment by smileydog** [comment]
Yeah, that would be a pain. Thanks for maintaining this project! It's been useful thus far.
