### ISSUE TITLE
Remove embed message

### ISSUE THREAD

**Issue by flupine** [Bjornskjald/miscord#108]
## Feature Request

I want to received message without embed to work with bots. I know i need to remove rich embeds but can you give me snippet to do this ?

**Comment by Bjornskjald** [comment]
Do you mean showing messages on Discord without embed, just plaintext?

**Comment by flupine** [comment]
Yes  i want juste plaintext like this : [Sender] : message :)

**Comment by Bjornskjald** [comment]
That's possible, "I could add a switch for that" 😄

**Comment by Bjornskjald** [comment]
@flupine Can you test it now?
