### ISSUE TITLE
Message from Facebook doesn't come on Discord

### ISSUE THREAD

**Issue by Bjornskjald** [Bjornskjald/miscord#110]
## Expected Behavior
Messaging works both ways

## Actual Behavior
Messages only arrive Discord -> Facebook, not Facebook -> Discord

## Steps to Reproduce the Problem

  1. Download the latest version
  1. Try to send a message from Facebook

## Specifications

  - Platform: Windows 10 / Windows 7 / Ubuntu
  - Version (can be found in package.json): 2.5.2
  - Node.js version (`node -v`): v8.9.1

**Comment by Bjornskjald** [comment]
@wdbrs @stanfear Could you check it now with 2.5.3? Works for me

**Comment by wdbrs** [comment]
I updated, I'm seeing version 2.5.3 in package.json, and Node.js is v8.10.0.  Still blank messages.  Tried the update on the other system as well, still blank.

**Comment by Bjornskjald** [comment]
@wdbrs how about now?

**Comment by wdbrs** [comment]
With version 2.6.3, still having blank messages
![2 6 3](https://user-images.githubusercontent.com/30547415/37563492-4df45682-2a58-11e8-8598-9c9052a928c0.jpg)

**Comment by wdbrs** [comment]
So I thought I'd mention that in GitHub Desktop, after installing and running the new version, I see that two files are changed locally, package.json and package-lock.json.  In package-lock.json the hex code on line 374 has been altered, right after `    "version": "github:schmavery/facebook-chat-api#`.  It looks like it's changing APIs.  I don't know if that is expected or not

**Comment by Bjornskjald** [comment]
@wdbrs you can find a commit saying "updated dependencies", so it's expected. The "hex code" is hash of the commit in facebook-chat-api repo

**Comment by Bjornskjald** [comment]
Can you change log level to `silly` and look for logs starting with `messengerListener`?

**Comment by wdbrs** [comment]
That's a pretty silly level of logging to be sure!  I can't tell what exactly you would need to know on the facebookListener sections, anything in particular?

Reading on though, under the discordListener logs, I see the bot can read it's own blank message, the info is in there in the embedded part, it is just invisible for me for some reason.  I'm viewing the discord messages on the web client in Chrome, and the Android app if that's important.

The main difference I see is as follows:

A working message sent from discord contains
`sill discordListener   content: 'testing from discord',`
and no embeds, a bit further down
`sill discordListener   embeds: [],`

A non working message sent from facebook, but then read and logged by discordListener contains
`sill discordListener   content: '',`
and instead shows the desired text under
```sill discordListener   embeds:
sill discordListener    [ MessageEmbed {
sill discordListener        message: [Circular],
sill discordListener        type: 'rich',
sill discordListener        title: undefined,
sill discordListener        description: 'testing from facebook',

**Comment by Bjornskjald** [comment]
So... it should work, I don't know why it doesn't  
Everything is like it should be, content in the second message should be empty because it's contained in the embed like you showed

**Comment by wdbrs** [comment]
Got it. Ugh, simple setting problem
![solution](https://user-images.githubusercontent.com/30547415/37565081-b59cba7a-2a78-11e8-9ec1-9be8bb557656.jpg)

**Comment by Bjornskjald** [comment]
...what  
That was the problem?

**Comment by wdbrs** [comment]
Yes, that was all apparently.  Better add that to the setup instructions, I'm sure I'm not the only one who's turned that setting off, previews really clutter up the chat

**Comment by wdbrs** [comment]
I didn't know it was an embed, searching for Discord embed problems showed this solution right away

**Comment by wdbrs** [comment]
Oh man, I hope this didn't drive you crazy!

**Comment by Bjornskjald** [comment]
Maybe a little bit? 😄 But it's nice it got sorted out, so others won't have the same issue
