### ISSUE TITLE
The get channel

### ISSUE THREAD

**Issue by RobCraftNet** [Bjornskjald/miscord#117]
![54454](https://user-images.githubusercontent.com/24510243/37559110-8c36f768-29f6-11e8-973c-15b94b47feed.PNG)
## Expected Behavior
The  get the channel get me an error 

## Steps to Reproduce the Problem

  1.get the bot start on
  1.send to on Facebook so get type error create the channel
  1.stop the bot so get me some error

## Specifications

  - Platform: Windows
  - Version (can be found in package.json): 2.6.2
  - Node.js version (`node -v`):8.6.0

**Comment by Bjornskjald** [comment]
@RobCraftNet Ok, I know why this happens. I'll fix it in 10 minutes

**Comment by RobCraftNet** [comment]
ok

**Comment by Bjornskjald** [comment]
@RobCraftNet Fixed, try now

**Comment by RobCraftNet** [comment]
ok
