### ISSUE TITLE
can get the bot start

### ISSUE THREAD

**Issue by RobCraftNet** [Bjornskjald/miscord#119]
## Expected Behavior
![7845](https://user-images.githubusercontent.com/24510243/37560781-314c80f6-2a15-11e8-9e81-bd8c009d70c8.PNG)
do not startup 

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Platform: Windows
  - Version (can be found in package.json):2.6.3
  - Node.js version (`node -v`):8.6.0

**Comment by Bjornskjald** [comment]
can you check your Discord token if it's correct?

**Comment by RobCraftNet** [comment]
ok

**Comment by RobCraftNet** [comment]
ok my discord token was not working and  generate a new token
