### ISSUE TITLE
The bot get me form node

### ISSUE THREAD

**Issue by RobCraftNet** [Bjornskjald/miscord#121]
## Expected Behavior
![bo99](https://user-images.githubusercontent.com/24510243/37571672-30e0d498-2ad6-11e8-8bee-9d700799139f.PNG)

## Steps to Reproduce the Problem

  1.the bot start
  1.send an over on discord and Facebook 
  1.and a for the node for it

## Specifications

  - Platform: windows 
  - Version (can be found in package.json):2.6.4
  - Node.js version (`node -v`):8.6.0

**Comment by mind12** [comment]
I have a very similar issue with this version:

`[TAILING] Tailing last 15 lines for [miscord] process (change the value with --lines option)
/root/.pm2/logs/miscord-out-1.log last 15 lines:
/root/.pm2/logs/miscord-error-1.log last 15 lines:
1|miscord  | info login Launching Miscord v2.6.4
1|miscord  | info login Logging in...
1|miscord  | info login Log level: info
1|miscord  | info updateNotifier Checking for updates...
1|miscord  | info login Logging in to Discord...
1|miscord  | info login Logged in to Discord
1|miscord  | info login Got Discord channels list
1|miscord  | info login Logging in to Facebook...
1|miscord  | info login Logged in

1|miscord  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
1|miscord  | DiscordAPIError: Cannot send an empty message
1|miscord  |     at item.request.gen.end (/opt/miscord/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
1|miscord  |     at then (/opt/miscord/node_modules/snekfetch/src/index.js:213:21)
1|miscord  |     at <anonymous>
1|miscord  |     at process._tickCallback (internal/process/next_tick.js:118:7)`

**Comment by Bjornskjald** [comment]
@RobCraftNet @mind12 It's probably related with #120, would you be able to change log level to `silly` and find logs with `createEmbed`?

**Comment by mind12** [comment]
Hey,

i just went back to release v2.6.2 and it's working. Sry I can't check the logs for you right now, but I'm ready to help you in the evening (CET) after raids end.

**Comment by Bjornskjald** [comment]
So... yup, it's because that PR. I'll try to fix that around 5pm

**Comment by Bjornskjald** [comment]
Nevermind, fixed it.
@mind12 will you be able to update it now?

**Comment by mind12** [comment]
@Bjornskjald I will update it soon and get back to you.

**Comment by RobCraftNet** [comment]
Ok

**Comment by RobCraftNet** [comment]
I will update when i get some time do I could do it while my school time

**Comment by RobCraftNet** [comment]
Look do good fix at error so thank you

**Comment by mind12** [comment]
@Bjornskjald 
I just got another exception with the latest version. 
A bot restart solved it but I don't know what triggered the exception.

1|miscord  | ERR!
1|miscord  |  listen Error: ESOCKETTIMEDOUT
1|miscord  | ERR! listen     at ClientRequest.<anonymous> (/opt/miscord/node_modules/request/request.js:813:19)
1|miscord  | ERR! listen     at Object.onceWrapper (events.js:219:13)
1|miscord  | ERR! listen     at ClientRequest.emit (events.js:127:13)
1|miscord  | ERR! listen     at ClientRequest.emit (domain.js:421:20)
1|miscord  | ERR! listen     at TLSSocket.emitTimeout (_http_client.js:702:34)
1|miscord  | ERR! listen     at Object.onceWrapper (events.js:219:13)
1|miscord  | ERR! listen     at TLSSocket.emit (events.js:127:13)
1|miscord  | ERR! listen     at TLSSocket.emit (domain.js:421:20)
1|miscord  | ERR! listen     at TLSSocket.Socket._onTimeout (net.js:419:8)
1|miscord  | ERR! listen     at ontimeout (timers.js:466:11)
1|miscord  | ERR! listen     at tryOnTimeout (timers.js:304:5)
1|miscord  | ERR! listen     at Timer.listOnTimeout (timers.js:267:5)
1|miscord  | ERR! listen  { Error: ESOCKETTIMEDOUT
1|miscord  | ERR! listen     at ClientRequest.<anonymous> (/opt/miscord/node_modules/request/request.js:813:19)
1|miscord  | ERR! listen     at Object.onceWrapper (events.js:219:13)
1|miscord  | ERR! listen     at ClientRequest.emit (events.js:127:13)
1|miscord  | ERR! listen     at ClientRequest.emit (domain.js:421:20)
1|miscord  | ERR! listen     at TLSSocket.emitTimeout (_http_client.js:702:34)
1|miscord  | ERR! listen     at Object.onceWrapper (events.js:219:13)
1|miscord  | ERR! listen     at TLSSocket.emit (events.js:127:13)
1|miscord  | ERR! listen     at TLSSocket.emit (domain.js:421:20)
1|miscord  | ERR! listen     at TLSSocket.Socket._onTimeout (net.js:419:8)
1|miscord  | ERR! listen     at ontimeout (timers.js:466:11)
1|miscord  | ERR! listen     at tryOnTimeout (timers.js:304:5)
1|miscord  | ERR! listen     at Timer.listOnTimeout (timers.js:267:5)
1|miscord  | ERR! listen   cause: { Error: ESOCKETTIMEDOUT
1|miscord  | ERR! listen     at ClientRequest.<anonymous> (/opt/miscord/node_modules/request/request.js:813:19)
1|miscord  | ERR! listen     at Object.onceWrapper (events.js:219:13)
1|miscord  | ERR! listen     at ClientRequest.emit (events.js:127:13)
1|miscord  | ERR! listen     at ClientRequest.emit (domain.js:421:20)
1|miscord  | ERR! listen     at TLSSocket.emitTimeout (_http_client.js:702:34)
1|miscord  | ERR! listen     at Object.onceWrapper (events.js:219:13)
1|miscord  | ERR! listen     at TLSSocket.emit (events.js:127:13)
1|miscord  | ERR! listen     at TLSSocket.emit (domain.js:421:20)
1|miscord  | ERR! listen     at TLSSocket.Socket._onTimeout (net.js:419:8)
1|miscord  | ERR! listen     at ontimeout (timers.js:466:11)
1|miscord  | ERR! listen     at tryOnTimeout (timers.js:304:5)
1|miscord  | ERR! listen     at Timer.listOnTimeout (timers.js:267:5) code: 'ESOCKETTIMEDOUT', connect: false },
1|miscord  | ERR! listen   isOperational: true,
1|miscord  | ERR! listen   code: 'ESOCKETTIMEDOUT',
1|miscord  | ERR! listen   connect: false }
1|miscord  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
1|miscord  | TypeError: Cannot read property 'threadID' of undefined
1|miscord  |     at module.exports.opts (/opt/miscord/lib/listeners/facebook.js:19:55)
1|miscord  |     at config.facebook.client.listen (/opt/miscord/index.js:12:51)
1|miscord  |     at /opt/miscord/node_modules/facebook-chat-api/src/listen.js:370:9
1|miscord  |     at tryCatcher (/opt/miscord/node_modules/bluebird/js/main/util.js:26:23)
1|miscord  |     at Promise._settlePromiseFromHandler (/opt/miscord/node_modules/bluebird/js/main/promise.js:510:31)
1|miscord  |     at Promise._settlePromiseAt (/opt/miscord/node_modules/bluebird/js/main/promise.js:584:18)
1|miscord  |     at Promise._settlePromises (/opt/miscord/node_modules/bluebird/js/main/promise.js:700:14)
1|miscord  |     at Async._drainQueue (/opt/miscord/node_modules/bluebird/js/main/async.js:123:16)
1|miscord  |     at Async._drainQueues (/opt/miscord/node_modules/bluebird/js/main/async.js:133:10)
1|miscord  |     at Immediate.Async.drainQueues [as _onImmediate] (/opt/miscord/node_modules/bluebird/js/main/async.js:15:14)
1|miscord  |     at runCallback (timers.js:763:18)
1|miscord  |     at tryOnImmediate (timers.js:734:5)
1|miscord  |     at processImmediate (timers.js:716:5)
1|miscord  |     at process.topLevelDomainCallback (domain.js:101:23)

**Comment by Bjornskjald** [comment]
It was caused by your internet, maybe connection break?

**Comment by tkhquang** [comment]
@Bjornskjald 
So after connection break, the bot stop working? Is there a way I can make it automatically reconnect everytime the internet is down?

**Comment by Bjornskjald** [comment]
I think it will reconnect itself... but if it doesn't you can use it with [`pm2`](http://pm2.keymetrics.io/) to auto-restart it

**Comment by mind12** [comment]
@Bjornskjald 
I use pm2 to manage the bot but how will it know that it's disconnected?
Could you help us how to restart the bot automatically if it's disconnected?

**Comment by Bjornskjald** [comment]
If it's disconnected it should reconnect... use pm2 when it exits on disconnect or crash

**Comment by RobCraftNet** [comment]
![gyuioiugfghjkoihg](https://user-images.githubusercontent.com/24510243/37615813-8c294e9e-2b84-11e8-9caa-6b06385523e4.PNG) I get an error for the rich embed decription may not exceed 2048 characters

**Comment by Bjornskjald** [comment]
So the Facebook message have to be too long apparently

**Comment by RobCraftNet** [comment]
yea but look all my chat on other account for it to see the long message for it

**Comment by RobCraftNet** [comment]
![bot_jkl](https://user-images.githubusercontent.com/24510243/37616986-0c66f342-2b88-11e8-994d-75206b894f95.PNG)
The get an error for it was a video form another facebook messenger

**Comment by Bjornskjald** [comment]
That's... weird. I don't know why this happens.

**Comment by RobCraftNet** [comment]
yap the bot I host now we do weather alert for spc and National Weather Service too
