### ISSUE TITLE
Make the Discord's channel rename optional

### ISSUE THREAD

**Issue by WM-MarcoBatista** [Bjornskjald/miscord#127]
Consider making the Discord's channel rename an optional feature in the configuration.
As an example, we’re trying to connect the **general** channel to the Facebook Goup called **Pokemon Go - Madeira** and we would like to keep both names as they are. Currently the Discord channel is renamed to the Facebook Group.

**Comment by Bjornskjald** [comment]
@WM-MarcoBatista I'll see what I can do _(maybe i'll add a switch for it)_

**Comment by WM-MarcoBatista** [comment]
It is working, now we can fully implement this on our server.
Thank you ;)
