### ISSUE TITLE
Unable to send Discord->Messenger messages after Messenger group is renamed

### ISSUE THREAD

**Issue by smileydog** [Bjornskjald/miscord#131]
## Expected Behavior

Bridge continues to function after Messenger room is renamed.

## Actual Behavior

Discord messages are not sent to the Facebook Messenger group if the group is renamed. In order to resolve, appstate.json needs to be deleted and miscord restarted. Once this happens, miscord creates a new duplicate channel with the same Facebook Messenger name.

## Steps to Reproduce the Problem

  1. Create facebook user and group, discord, etc.
  2. Clone miscord, configure config.json, npm install, npm start 
  3. Users send messages on both sides of bridge (Messenger & Discord)
  4. Facebook Messenger user renames room
  5. Users attempt to send messages on both sides of bridge. Bridge sends Facebook Messenger messages to Discord, but does not send message from Discord to Facebook Messenger

## Specifications

  - Platform: Win 10
  - Version (can be found in package.json): 2.6.10
  - Node.js version (`node -v`): 8.10.0

**Comment by Bjornskjald** [comment]
Cannot reproduce. Can you change your log level to `silly` and give me the logs? You can remove any personal info.

**Comment by smileydog** [comment]
Have to run errands, but I'll definitely send soon. Thanks again @Bjornskjald.

**Comment by smileydog** [comment]
Ok back. Figured I fudged up again with Discord permissions, so I reset everything and the renaming is working well. Thanks @Bjornskjald! Closing ticket.
