### ISSUE TITLE
Need help handling socket timeout

### ISSUE THREAD

**Issue by mind12** [Bjornskjald/miscord#141]
I need help how to handle automatically this occasions. 
I would like to auto restart the application when this happens. 

## Expected Behavior
Restart after socket timeout.

## Actual Behavior
Application crash.

## Steps to Reproduce the Problem

  1. Internet outage.
  
## Specifications

  - Platform: Ubuntu 16
  - Version (can be found in package.json): v2.7.1
  - Node.js version (`node -v`): v9.7.1

## Error message

28-03 06:45:03.051: ERR!28-03 06:45:03.052:  listen Error: ESOCKETTIMEDOUT
ERR! listen     at ClientRequest.<anonymous> (/opt/miscord/node_modules/request/request.js:813:19)
ERR! listen     at Object.onceWrapper (events.js:219:13)
ERR! listen     at ClientRequest.emit (events.js:127:13)
ERR! listen     at ClientRequest.emit (domain.js:421:20)
ERR! listen     at TLSSocket.emitTimeout (_http_client.js:702:34)
ERR! listen     at Object.onceWrapper (events.js:219:13)
ERR! 28-03 06:45:03.052: listen     at TLSSocket.emit (events.js:127:13)
ERR! listen     at TLSSocket.emit (domain.js:421:20)
ERR! listen     at TLSSocket.Socket._onTimeout (net.js:419:8)
28-03 06:45:03.053: ERR! listen     at ontimeout (timers.js:466:11)
ERR!28-03 06:45:03.053:  listen     at tryOnTimeout (timers.js:304:5)
ERR! 28-03 06:45:03.053: listen     at Timer.listOnTimeout (timers.js:267:5)
ERR! listen28-03 06:45:03.053:   { Error: ESOCKETTIMEDOUT
ERR! listen     at ClientRequest.<anonymous> (/opt/miscord/node_modules/request/request.js:813:19)
28-03 06:45:03.053: ERR! listen     at Object.onceWrapper (events.js:219:13)
28-03 06:45:03.053: ERR! listen     at ClientRequest.emit (events.js:127:13)
28-03 06:45:03.054: ERR! listen     at ClientRequest.emit (domain.js:421:20)
28-03 06:45:03.054: ERR! listen     at TLSSocket.emitTimeout (_http_client.js:702:34)
ERR!28-03 06:45:03.054:  listen     at Object.onceWrapper (events.js:219:13)
ERR!28-03 06:45:03.054:  listen     at TLSSocket.emit (events.js:127:13)
ERR!28-03 06:45:03.054:  listen     at TLSSocket.emit (domain.js:421:20)
ERR! 28-03 06:45:03.054: listen     at TLSSocket.Socket._onTimeout (net.js:419:8)
ERR! 28-03 06:45:03.054: listen     at ontimeout (timers.js:466:11)
ERR!28-03 06:45:03.055:  listen     at tryOnTimeout (timers.js:304:5)
ERR!28-03 06:45:03.055:  listen     at Timer.listOnTimeout (timers.js:267:5)
ERR!28-03 06:45:03.055:  listen   cause: { Error: ESOCKETTIMEDOUT
ERR!28-03 06:45:03.055:  listen     at ClientRequest.<anonymous> (/opt/miscord/node_modules/request/request.js:813:19)
ERR! 28-03 06:45:03.055: listen     at Object.onceWrapper (events.js:219:13)
ERR! 28-03 06:45:03.055: listen     at ClientRequest.emit (events.js:127:13)
ERR! 28-03 06:45:03.055: listen     at ClientRequest.emit (domain.js:421:20)
ERR! 28-03 06:45:03.056: listen     at TLSSocket.emitTimeout (_http_client.js:702:34)
ERR!28-03 06:45:03.056:  listen     at Object.onceWrapper (events.js:219:13)
ERR!28-03 06:45:03.056:  listen     at TLSSocket.emit (events.js:127:13)
ERR!28-03 06:45:03.056:  listen     at TLSSocket.emit (domain.js:421:20)
ERR!28-03 06:45:03.056:  listen     at TLSSocket.Socket._onTimeout (net.js:419:8)
ERR!28-03 06:45:03.056:  listen     at ontimeout (timers.js:466:11)
ERR!28-03 06:45:03.056:  listen     at tryOnTimeout (timers.js:304:5)
ERR!28-03 06:45:03.056:  listen     at Timer.listOnTimeout (timers.js:267:5) code: 'ESOCKETTIMEDOUT', connect: false },
ERR!28-03 06:45:03.057:  listen   isOperational: true,
ERR!28-03 06:45:03.057:  listen   code: 'ESOCKETTIMEDOUT',
ERR!28-03 06:45:03.057:  listen   connect: false }
28-03 06:45:03.059: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'threadID' of undefined
    at module.exports.opts (/opt/miscord/lib/listeners/facebook.js:19:48)
    at config.facebook.client.listen (/opt/miscord/index.js:12:51)
    at /opt/miscord/node_modules/facebook-chat-api/src/listen.js:443:11
    at tryCatcher (/opt/miscord/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/miscord/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/opt/miscord/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/opt/miscord/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/opt/miscord/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/miscord/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/miscord/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:101:23)

**Comment by Bjornskjald** [comment]
I saw this error before, the "Cannot read property threadID of undefined" worries me the most

**Comment by mind12** [comment]
I think this is a timeout issue, my Internet connection went down and after some time the connection to facebook timed out. That caused the cannot read property message.

I can test this later by restricting my machine on the firewall.
