### ISSUE TITLE
GIF's causing Crash

### ISSUE THREAD

**Issue by ShinNinth** [Bjornskjald/miscord#153]
## Expected Behavior
Not exactly sure what the expected behavior for GIF's was originally it just displayed a link in discord.

## Actual Behavior
Crashes with the following error:

info messengerListener Got a Messenger message
ERR! error TypeError: Cannot read property 'author' of undefined
ERR! error     at getChannel.then (C:\messenger-discord-master\miscord-master\lib\listeners\messenger.js:104:53)
ERR! error     at <anonymous>
ERR! error     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR! error  { TypeError: Cannot read property 'author' of undefined
ERR! error     at getChannel.then (C:\messenger-discord-master\miscord-master\lib\listeners\messenger.js:104:53)
ERR! error     at <anonymous>
ERR! error     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR! error   stack: 'TypeError: Cannot read property \'author\' of undefined\n    at getChannel.then (C:\\messenger-discord-master\\miscord-master\\lib\\listeners\\messenger.js:104:53)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! messenger-discord@2.7.7 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the messenger-discord@2.7.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dedicated\AppData\Roaming\npm-cache\_logs\2018-03-31T05_59_45_848Z-debug.log

## Steps to Reproduce the Problem

  1. run npm start
  2. send gif in messenger
  3. receive crash

## Specifications

  - Platform: Windows
  - Version (can be found in package.json):2.7.7
  - Node.js version (`node -v`): v8.11.0
[2018-03-31T05_59_45_848Z-debug.log](https://github.com/Bjornskjald/miscord/files/1865207/2018-03-31T05_59_45_848Z-debug.log)

**Comment by ShinNinth** [comment]
A side note if you force logging in for Messenger Settings the Gif crash doesnt happen

**Comment by Bjornskjald** [comment]
the "force login" thing must have been a coincidence

**Comment by Bjornskjald** [comment]
Okay, found it.
https://github.com/Bjornskjald/miscord/blob/959c000f54616351fa43bbb6cc8dd0903ec03aab/lib/listeners/messenger.js#L104
I'll try to fix it, but I'm working from phone so it'll take some time to even setup git on there

**Comment by ShinNinth** [comment]
Doing some testing some one posted a photo to messenger that caused the error even after force login

**Comment by Bjornskjald** [comment]
Can you check it now? Force login variable is not related to any of this...

**Comment by ShinNinth** [comment]
Just tested and it seems to be working well on initial photo and gif tests
