### ISSUE TITLE
Image only Messenger messages crash NPM

### ISSUE THREAD

**Issue by Nedihardt97** [Bjornskjald/miscord#157]
## Expected Behavior
For images sent to messenger with only an image to be sent to discord

## Actual Behavior
NPM crashes

## Steps to Reproduce the Problem

  1. Sent an image on Messenger Group, caused immediate crash

## Steps to Solve the Problem

  1. Have not gotten the chance to turn off embeds, but it would likely prevent these crashes, but you might imagine that it would preferable to resolve this rather than having to turn off embeds entirely

## Specifications

  - Platform:
  - OS: Win 10
  - Version: 2.7.4
  - Node.js version: v8.11.0

##Relevant log section
ERR! error TypeError: Cannot read property 'author' of undefined
ERR! error     at getChannel.then (C:\Users\Neidhardt\miscord\lib\listeners\messenger.js:104:53)
ERR! error     at <anonymous>
ERR! error     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR! error  { TypeError: Cannot read property 'author' of undefined
ERR! error     at getChannel.then (C:\Users\Neidhardt\miscord\lib\listeners\messenger.js:104:53)
ERR! error     at <anonymous>
ERR! error     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR! error   stack: 'TypeError: Cannot read property \'author\' of undefined\n    at getChannel.then (C:\\Users\\Neidhardt\\miscord\\lib\\listeners\\messenger.js:104:53)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! messenger-discord@2.7.4 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the messenger-discord@2.7.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Neidhardt\AppData\Roaming\npm-cache\_logs\2018-04-01T02_10_42_391Z-debug.log

##Data from expanded log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle messenger-discord@2.7.4~prestart: messenger-discord@2.7.4
6 info lifecycle messenger-discord@2.7.4~start: messenger-discord@2.7.4
7 verbose lifecycle messenger-discord@2.7.4~start: unsafe-perm in lifecycle true
8 verbose lifecycle messenger-discord@2.7.4~start: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Neidhardt\miscord\node_modules\.bin;C:\Users\Neidhardt\AppData\Roaming\npm;C:\Program Files (x86)\nodejs\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\GTK2-Runtime\lib;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Program Files (x86)\nodejs\;C:\Users\Neidhardt\AppData\Local\Microsoft\WindowsApps;C:\Users\Neidhardt\AppData\Roaming\npm
9 verbose lifecycle messenger-discord@2.7.4~start: CWD: C:\Users\Neidhardt\miscord
10 silly lifecycle messenger-discord@2.7.4~start: Args: [ '/d /s /c', 'node index.js' ]
11 silly lifecycle messenger-discord@2.7.4~start: Returned: code: 1  signal: null
12 info lifecycle messenger-discord@2.7.4~start: Failed to exec start script
13 verbose stack Error: messenger-discord@2.7.4 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid messenger-discord@2.7.4
15 verbose cwd C:\Users\Neidhardt\miscord
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.11.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error messenger-discord@2.7.4 start: `node index.js`
22 error Exit status 1
23 error Failed at the messenger-discord@2.7.4 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Bjornskjald** [comment]
It's already fixed in 2.7.7, closing as duplicate

**Comment by Bjornskjald** [comment]
(but if it happens again, just paste new logs)
