### ISSUE TITLE
Bot not sending links from FB messenger to Discord

### ISSUE THREAD

**Issue by lbpogo562** [Bjornskjald/miscord#159]
## Expected Behavior
When link is posted on FB messenger chat, the link is sent to the Discord channel. 

Hosting bot on glitch.com. To host, I followed this tutorial https://anidiotsguide_old.gitbooks.io/discord-js-bot-guide/content/other-guides/hosting-on-glitchcom.html
Per tutorial, made 3 changes: added watch.json, added express.js dependency to package.json and add express.js code to index.js, added `"engines": { "node": "8.10.0" }` to package.json

## Actual Behavior
Link is not sent from FB messenger chat to Discord Channel. Same issue for bot running on local machine and running on glitch.com. Bo

## Steps to Reproduce the Problem

  1. Sent link on Facebook messenger chat
  1. No link appears on Discord channel
  1. 

## Specifications

  - Platform: Glitch.com
  - Version (can be found in package.json): 2.7.8
  - Node.js version (`node -v`): 8.10.0

**Comment by Bjornskjald** [comment]
> expected to work same as running on local machine.

> add code for express.js to index.js

Uh, come on... show me your index.js, also it would be good if you can provide logs on silly mode

**Comment by lbpogo562** [comment]
The index.js is code below. New to programming, don't know how to send log via silly mode. If needed, can send if I get some directions. Also, images are being sent now, but links do not. Thanks for you help!

const express = require("express")
const expressApp = express()
expressApp.get("/", (req, res) => res.json("OK"))
expressApp.listen(process.env.PORT)

require('./lib/logger.js')

const sendError = require('./lib/error.js')
const login = require('./lib/login/login.js')

const discordListener = require('./lib/listeners/discord.js')
const messengerListener = require('./lib/listeners/messenger.js')

login().then(config => {
  // when got a discord message
  config.discord.client.on('message', message => discordListener({config, message}))

  // when got a messenger message
  config.messenger.client.listen((err, message) => messengerListener({config, err, message}))
}).catch(sendError)

**Comment by lbpogo562** [comment]
Update - links do not work on local machine either. I will update my original comment to reflect the issue.

**Comment by lbpogo562** [comment]
Update: The bug with a link not sending from FB messenger to Discord is only in FB group chats. I had tested sending links in private messages from FB to Discord and it works.

**Comment by lbpogo562** [comment]
Thanks for answering! For whatever reason, links are getting sent in from the FB group chats now. I would say it's been resolved. Was not working yesterday, but working today. Very unclear what/why caused it to not work then. Please feel free to close this issue.
