### ISSUE TITLE
Bot doesn't find recategorized channel after restart

### ISSUE THREAD

**Issue by tehstone** [Bjornskjald/miscord#171]
## Expected Behavior
Bot should recognize when channels have been moved into a new category

## Actual Behavior
Bot creates a new channel in default category and relays messages to both the old and new channels.

## Steps to Reproduce the Problem
1. Start the bot and let it relay messages from FB to Discord
2. Move the channel it has created into a new category
3. Restart the bot and send more messages from FB
4. New channel will appear in the default category and relayed messages will appear in both channels.

## Specifications

  - Platform:
  - Version (`miscord -v`):
  - Node.js version (`node -v`):

**Comment by Bjornskjald** [comment]
`both the old and new channels`  
that's the part which worries me  
are you sure about that?

**Comment by Bjornskjald** [comment]
also, bot recognizes "its" channels by the category, so...
don't move these channels from bot's category and everything will work

**Comment by Bjornskjald** [comment]
oh, there is a way you can try: https://github.com/Bjornskjald/miscord/wiki/Custom-mapping  
I think it will work with channel ID, if not then idk

**Comment by tehstone** [comment]
So I can't put the channels the bot generates into new categories? We're using this for 4 different facebook chats and would ideally have those split into 2 different categories

**Comment by Bjornskjald** [comment]
You can use 2 bots, each pointing at a different category and having different chats in the whitelist=

**Comment by Bjornskjald** [comment]
Or, as I said, custom mapping to point Miscord at the correct channels

**Comment by tehstone** [comment]
So with the custom mapping all messages from every mapped FB chat will show up in the one discord channel?

And will all messages from that discord channel get sent to each mapped FB chat?

And will messages be relayed from one mapped FB chat to another?

**Comment by Bjornskjald** [comment]
No, custom mapping specifies which Discord channel corresponds to which Facebook chat.  
It could work with multiple channels, but now it's only one-to-one.
