### ISSUE TITLE
the bot is do not work

### ISSUE THREAD

**Issue by RobCraftNet** [Bjornskjald/miscord#200]
_If you have a question, ask on the [Miscord Support server](https://discord.gg/DkmTvVz) instead of 

## Expected Behavior
when sending over discord or Facebook do not work send for DiscordAPIError

## Actual Behavior
![9797](https://user-images.githubusercontent.com/24510243/38787718-bb365518-40fd-11e8-9643-117e83d9eed4.PNG)

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Platform: win 10
  - Version (`miscord -v`): 3.1.0
  - Node.js version (`node -v`):8.10.0

**Comment by talormanda** [comment]
Same issue on linux.
