### ISSUE TITLE
have issues with the bot api

### ISSUE THREAD

**Issue by RobCraftNet** [Bjornskjald/miscord#208]
_If you have a question, ask on the [Miscord Support server](https://discord.gg/DkmTvVz) instead of _  
## Expected Behavior
![41](https://user-images.githubusercontent.com/24510243/39005293-db71673c-43cd-11e8-97b6-1c23e287a498.PNG)

## Steps to Reproduce the Problem

  1.update the bot
  2.npm i
  3. npm update
  4. npm start
  5. and get an error for it

## Specifications

  - Platform: win 10
  - Version (`miscord -v`):3.1.4 - 3.1.5
  - Node.js version (`node -v`):8.10.0 

_Sent from my LG Aristo using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Bjornskjald** [comment]
Can you run it again with log level set to `silly` in the config?

**Comment by RobCraftNet** [comment]
yea hole

**Comment by RobCraftNet** [comment]
yea it get the files for log form silly see on log files

**Comment by RobCraftNet** [comment]
@Bjornskjald see with put on silly for it 
>miscord@3.1.4 start C:\Users\robbi\Desktop\miscord-master
> node bin/index.js

info login Launching Miscord v3.1.4
info login Logging in...
info login Log level: info
info updateNotifier Checking for updates...
info login Logging in to Discord...
info login Logged in to Discord
ERR! error DiscordAPIError: Invalid Form Body
ERR! error name: This field is required
ERR! error     at item.request.gen.end (C:\Users\robbi\Desktop\miscord-master\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:71:65)
ERR! error     at then (C:\Users\robbi\Desktop\miscord-master\node_modules\snekfetch\src\index.js:215:21)
ERR! error     at <anonymous>
ERR! error     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR! error  { DiscordAPIError: Invalid Form Body
ERR! error name: This field is required
ERR! error     at item.request.gen.end (C:\Users\robbi\Desktop\miscord-master\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:71:65)
ERR! error     at then (C:\Users\robbi\Desktop\miscord-master\node_modules\snekfetch\src\index.js:215:21)
ERR! error     at <anonymous>
ERR! error     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR! error   stack: 'DiscordAPIError: Invalid Form Body\nname: This field is required\n    at item.request.gen.end (C:\\Users\\robbi\\Desktop\\miscord-master\\node_modules\\discord.js\\src\\client\\rest\\RequestHandlers\\Sequential.js:71:65)\n    at then (C:\\Users\\robbi\\Desktop\\miscord-master\\node_modules\\snekfetch\\src\\index.js:215:21)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
ERR! error   name: 'DiscordAPIError',
ERR! error   message: 'Invalid Form Body\nname: This field is required',
ERR! error   path: '/api/v7/guilds/413159476879949825/channels',
ERR! error   code: 50035 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! miscord@3.1.4 start: `node bin/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the miscord@3.1.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Bjornskjald** [comment]
That's still `info` log level, did you change it in the config?

**Comment by RobCraftNet** [comment]
yea

**Comment by RobCraftNet** [comment]
![capturet](https://user-images.githubusercontent.com/24510243/39006212-669bb0ae-43d0-11e8-82c1-4e6d07be323d.PNG)
yea put silly in config @Bjornskjald

**Comment by Bjornskjald** [comment]
Are you sure it's your config file from which you're running the Miscord?

**Comment by RobCraftNet** [comment]
Yea

**Comment by RobCraftNet** [comment]
@Bjornskjald Yea  i run the bot on my pc

_Sent from my LG Aristo using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by RobCraftNet** [comment]
@Bjornskjald Yea have in the config token and login password whit config 

_Sent from my LG Aristo using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by RobCraftNet** [comment]
@Bjornskjald ![](https://i.imgur.com/uaxKv7R.png) 

So at the of config.js files

_Sent from my LG Aristo using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Bjornskjald** [comment]
Uhh... can you run it once again and send me the logs?

**Comment by RobCraftNet** [comment]
Yea

**Comment by RobCraftNet** [comment]
@Bjornskjald here logs
Desktop\miscord-master>npm start

> miscord@3.1.4 start C:\Users\robbi\Desktop\miscord-master
> node bin/index.js

info login Launching Miscord v3.1.4
info login Logging in...
info login Log level: info
info updateNotifier Checking for updates...
info login Logging in to Discord...
info login Logged in to Discord
ERR! error DiscordAPIError: Invalid Form Body
ERR! error name: This field is required
ERR! error     at item.request.gen.end (C:\Users\robbi\Desktop\miscord-master\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:71:65)
ERR! error     at then (C:\Users\robbi\Desktop\miscord-master\node_modules\snekfetch\src\index.js:215:21)
ERR! error     at <anonymous>
ERR! error     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR! error  { DiscordAPIError: Invalid Form Body
ERR! error name: This field is required
ERR! error     at item.request.gen.end (C:\Users\robbi\Desktop\miscord-master\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:71:65)
ERR! error     at then (C:\Users\robbi\Desktop\miscord-master\node_modules\snekfetch\src\index.js:215:21)
ERR! error     at <anonymous>
ERR! error     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR! error   stack: 'DiscordAPIError: Invalid Form Body\nname: This field is required\n    at item.request.gen.end (C:\\Users\\robbi\\Desktop\\miscord-master\\node_modules\\discord.js\\src\\client\\rest\\RequestHandlers\\Sequential.js:71:65)\n    at then (C:\\Users\\robbi\\Desktop\\miscord-master\\node_modules\\snekfetch\\src\\index.js:215:21)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
ERR! error   name: 'DiscordAPIError',
ERR! error   message: 'Invalid Form Body\nname: This field is required',
ERR! error   path: '/api/v7/guilds/413159476879949825/channels',
ERR! error   code: 50035 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! miscord@3.1.4 start: `node bin/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the miscord@3.1.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by RobCraftNet** [comment]
[2018-04-19T16_30_16_391Z-debug.log](https://github.com/Bjornskjald/miscord/files/1929220/2018-04-19T16_30_16_391Z-debug.log)
[2018-04-19T16_31_54_801Z-debug.log](https://github.com/Bjornskjald/miscord/files/1929221/2018-04-19T16_31_54_801Z-debug.log)
[2018-04-19T16_39_10_392Z-debug.log](https://github.com/Bjornskjald/miscord/files/1929222/2018-04-19T16_39_10_392Z-debug.log)
[2018-04-19T16_48_55_336Z-debug.log](https://github.com/Bjornskjald/miscord/files/1929223/2018-04-19T16_48_55_336Z-debug.log)
[2018-04-19T17_46_48_302Z-debug.log](https://github.com/Bjornskjald/miscord/files/1929224/2018-04-19T17_46_48_302Z-debug.log)
[2018-04-19T17_55_29_624Z-debug.log](https://github.com/Bjornskjald/miscord/files/1929225/2018-04-19T17_55_29_624Z-debug.log)

@Bjornskjald 
here is all log form error with logs form

**Comment by Bjornskjald** [comment]
Those are NPM error logs, not Miscord.

**Comment by RobCraftNet** [comment]
but the log form miscord it not in files

**Comment by RobCraftNet** [comment]
When i get home will look on in miscord files logs yea

**Comment by RobCraftNet** [comment]
@Bjornskjald yea in files logs olay in .gitkeep forsee in logs form miscord do why put in logs

**Comment by RobCraftNet** [comment]
@Bjornskjald  have some error with new version 3.1.5 with have error discordapi so you get time thank you by RatingGull on discord

**Comment by RobCraftNet** [comment]
[2018-04-20_15-07-24.log](https://github.com/Bjornskjald/miscord/files/1932618/2018-04-20_15-07-24.log)
@Bjornskjald  here at one logs look for it so your welcome

**Comment by Bjornskjald** [comment]
It crashes here:  
https://github.com/Bjornskjald/miscord/blob/74d7f5d9cf22978d757c940cba64dd1493e03b8e/lib/login/discord.js#L29
but I don't know why...

**Comment by RobCraftNet** [comment]
Mm

**Comment by RobCraftNet** [comment]
@Bjornskjald can you look old version login discord.js 

_Sent from my LG Aristo using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Bjornskjald** [comment]
the only thing that changed was the status message

**Comment by RobCraftNet** [comment]
@Bjornskjald can be is code // set activity
    discord.user.setActivity('Miscord v' + require('../../package.json').version) when see version for form like code login discord.js 3.1.3

**Comment by Bjornskjald** [comment]
It shouldn't change anything in getting a list of channels .-.

**Comment by RobCraftNet** [comment]
mm see form 3.1.3 login discord.js see whit code

**Comment by RobCraftNet** [comment]
@Bjornskjald you back to version 3.1.3 look a code on login discord.js see at whit code

**Comment by ShinNinth** [comment]
Just a question are you updating your config.json when you update? I ran into errors like this going from one version to another and noticed that i had an older config and once i updated it to match the newer config the errors went away.

Just a thought.

**Comment by Bjornskjald** [comment]
@ShinNinth I guess you mean change from "facebook" to "messenger"...   
For 3 weeks on every launch there was a deprecation warning if you used the old name
