### ISSUE TITLE
Feature request: Allow certain messages to stay within their respective platform

### ISSUE THREAD

**Issue by simeonlg** [Bjornskjald/miscord#214]
Allow a message such as:
```!messengeronlyindicator Remember to check out discord at DISCORDLINK```
to be broadcast only in its respective platform.

This can be used to "advertise" with the discord link to the messenger group or to let users on discord know something about the other channels, which probably is not needed for the messenger group.

**Comment by Bjornskjald** [comment]
So... you want the bridge to ignore messages with certain prefixes?

**Comment by simeonlg** [comment]
Pretty much, a prefix seems to be the simplest solution

**Comment by Bjornskjald** [comment]
I think I'll be able to add it with other commands, but it's really *in progress* and I don't know when I'd be able to finish it.
