### ISSUE TITLE
Images are not shared between linked Messenger chats

### ISSUE THREAD

**Issue by tehstone** [Bjornskjald/miscord#220]
On my discord server, I have configured 2 Messenger chats to send messages between one another and for a single Discord channel to relay messages to those 2 Messenger chats. All text is transferred correctly, images sent from Discord appear in both Messenger chats, and images sent from one of the Messenger chats appear in Discord but not in the other Messenger chat.

**To Reproduce**
1. Link 2 Messenger chats
2. Map both Messenger chats to 1 Discord channel.
3. Send an image from 1 Messenger chat
4. Image will not appear in the other Messenger chat

**Expected behavior**
Image messages should relay between linked Messenger chats.

**Screenshots**
![miscord](https://user-images.githubusercontent.com/1518350/40073796-bd03907c-582c-11e8-9508-adaa255a1ff1.PNG)

**Specifications:**
 - OS: some linux distro
 - Version 3.2.2

**Comment by Bjornskjald** [comment]
Actually, I never finished it... I'll try to do it now
