### ISSUE TITLE
Duplicate messages

### ISSUE THREAD

**Issue by Thashiznets** [Bjornskjald/miscord#227]
In periods of inactivity, a chat that has a custom facebook messenger thread to a discord channel linking seems to flood duplicate messages periodically.

v3.3.2

**Comment by Thashiznets** [comment]
![c21aa34e-e891-40e1-8168-37c1e6c236ce](https://user-images.githubusercontent.com/2297007/40637629-5d63be80-6349-11e8-9031-cc5ad8e0f86b.jpeg)

**Comment by RobCraftNet** [comment]
Me too  but be the the wifi white the bot

**Comment by Bjornskjald** [comment]
Could you change the log level to silly and send me the logs when this happens?

**Comment by Thashiznets** [comment]
Yes I will set it now

**Comment by Thashiznets** [comment]
Sent log to your email thanks

**Comment by Bjornskjald** [comment]
@Thashiznets Sorry, didn't get your email yet...

**Comment by Thashiznets** [comment]
Ok it says sent but I forwarded it to you again, github@bjorn.ml

**Comment by tachyonicClock** [comment]
I'm having a similar issue. When a message is sent to the bot through messenger it will flood discord with duplicate messages.

**Comment by Thashiznets** [comment]
can do

**Comment by Bjornskjald** [comment]
...and?

**Comment by Thashiznets** [comment]
Looks for the most part solved. I think I saw maybe one duplicate message only lately but seems really a non issue now.

**Comment by Bjornskjald** [comment]
Alright, thanks.
