### ISSUE TITLE
Crash when sending a message from FB to Discord

### ISSUE THREAD

**Issue by sinkillerj** [Bjornskjald/miscord#233]
The bot is able to send messages from Discord to Facebook just fine, but when attempting to post from Facebook to Discord it exits with no error after "verb messengerListener Got Discord channel", miscord does not restart itself after this exit. I have tried both custom mapping, as well as letting it create its own channel. The channel is created but the message is still not posted.

Log Level Silly: https://pastebin.com/MzqW3tUV

**Comment by Bjornskjald** [comment]
It just exits, without any errors?

**Comment by sinkillerj** [comment]
Exactly, straight back to the terminal, its odd:
verb messengerListener Got Discord channel
pi@raspberrypi:~ $

**Comment by Bjornskjald** [comment]
Oh... I think I know why.
Is the picture of your chat set? Or is it empty and it just shows people from the group?

**Comment by sinkillerj** [comment]
The Discord has a icon, the Facebook chat does indeed just show a mosaic of people. I guess I will need to set one to resolve this crash?

**Comment by Bjornskjald** [comment]
Commit https://github.com/Bjornskjald/miscord/commit/56e9ce86e568fb7dfa25351f2d314fc327e819a0 fixes it, just wait for an update.

**Comment by sinkillerj** [comment]
Thanks for the fast response m8, loving your bot so far despite the minor issue.

**Comment by Bjornskjald** [comment]
Done, you should be able to update now.
