### ISSUE TITLE
Log Channel on Discord

### ISSUE THREAD

**Issue by fortepc** [Bjornskjald/miscord#250]
**Describe the solution you'd like**
Similar to the current implementation of the `miscord.ownerID` sending errors and fault messages to the owner, you could add a new configuration option, `discord.logchannel` where you'd specify a discord channel ID and miscord will post any errors or faults it gets into that channel. 

**Describe alternatives you've considered**

**Additional context**

**Comment by Bjornskjald** [comment]
Could log channel be merged with admin channel?

**Comment by fortepc** [comment]
I know I'd prefer it not be. I personally get a lot of Errors, I know that
I would prefer to have then separate so that my command Channel doesn't get
spammed with all those errors.

**Comment by Bjornskjald** [comment]
@fortepc How about a group DM? They you wouldn't need to worry about additional channels and permissions, when you have more than 1 owner they you would just put them as an array?
