### ISSUE TITLE
Bridge in 3rd channel isn't working both ways, only works Discord -> Messenger.

### ISSUE THREAD

**Issue by fortepc** [Bjornskjald/miscord#251]
I'm having an issue where miscord is not working in the 3rd of three mapped channels. Miscord isn't sending me any error messages, but it's simply not working. 

It sends messages from Discord to Messenger, but it isn't sending any messages from Messenger to Discord. The bot has it's needed permissions (infact, it has all permissions) and still isn't working for that one channel, despite working fine in the rest.

Will get silly logs when I can if needed.

**Comment by Bjornskjald** [comment]
So get the logs please, without logs I can only suggest you to read [troubleshooting](https://github.com/Bjornskjald/miscord/wiki/Troubleshooting)

**Comment by fortepc** [comment]
Sorry, my plan was to VNC into the server and get the logs shortly after posting this, but I got tied up. I will do that in a couple hours

**Comment by fortepc** [comment]
Okay, found my own problem while trying to get silly logs. It's not exactly a bug, but not exactly expected behavior. 

The new 3rd chat wasn't in the chat whitelist, but it was in the channels.yml. There should probably be some check to allow specifically mapped channels even if they're not on the whitelist.

**Comment by Bjornskjald** [comment]
Okay, I'll add it.
