### ISSUE TITLE
miscord failing upon launch

### ISSUE THREAD

**Issue by Nedihardt97** [Bjornskjald/miscord#252]
After running "npm start" in node.js command prompt, the following log is produced:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle messenger-discord@2.7.4~prestart: messenger-discord@2.7.4
6 info lifecycle messenger-discord@2.7.4~start: messenger-discord@2.7.4
7 verbose lifecycle messenger-discord@2.7.4~start: unsafe-perm in lifecycle true
8 verbose lifecycle messenger-discord@2.7.4~start: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Neidhardt\miscord\node_modules\.bin;C:\Users\Neidhardt\AppData\Roaming\npm;C:\Program Files (x86)\nodejs\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\GTK2-Runtime\lib;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Program Files (x86)\nodejs\;C:\WINDOWS\System32\OpenSSH\;C:\Users\Neidhardt\AppData\Local\Microsoft\WindowsApps;C:\Users\Neidhardt\AppData\Roaming\npm;
9 verbose lifecycle messenger-discord@2.7.4~start: CWD: C:\Users\Neidhardt\miscord
10 silly lifecycle messenger-discord@2.7.4~start: Args: [ '/d /s /c', 'node index.js' ]
11 silly lifecycle messenger-discord@2.7.4~start: Returned: code: 1  signal: null
12 info lifecycle messenger-discord@2.7.4~start: Failed to exec start script
13 verbose stack Error: messenger-discord@2.7.4 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid messenger-discord@2.7.4
15 verbose cwd C:\Users\Neidhardt\miscord
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.11.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error messenger-discord@2.7.4 start: `node index.js`
22 error Exit status 1
23 error Failed at the messenger-discord@2.7.4 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

------------------------------------------------------------------------------------------------------------------
I have tried to update, but updates continually fail due to dependencies which fail to update as well.

**Comment by Bjornskjald** [comment]
but... that log doesn't tell me anything
and in the console just before path to that log you have a message to not use this log because it's meaningless
screenshot from cmd would be the best

**Comment by Bjornskjald** [comment]
also, you're using `messenger-discord` which is waaay older than the latest

**Comment by Nedihardt97** [comment]
![image](https://user-images.githubusercontent.com/25507769/41984115-d6c629a0-79fd-11e8-90e1-14121f706a4a.png)

**Comment by Nedihardt97** [comment]
And yes, I have tried to update to the latest version you have, but it fails due to dependencies which I can't seem to resolve either

**Comment by Bjornskjald** [comment]
did you install Miscord through git?

**Comment by Nedihardt97** [comment]
I did.
tried "npm install -g miscord"
and: "npm i npm"
which both give the same outputs of needed peer dependencies which I can't install either

**Comment by Nedihardt97** [comment]
![image](https://user-images.githubusercontent.com/25507769/41984353-7a5bd754-79fe-11e8-871d-0a8482fb0a02.png)

**Comment by Bjornskjald** [comment]
so just run Miscord by `miscord`, not `npm start`

**Comment by Bjornskjald** [comment]
as you're installing it globally

**Comment by Nedihardt97** [comment]
![image](https://user-images.githubusercontent.com/25507769/41984473-c3dab5ee-79fe-11e8-9570-7412029a5ee4.png)

**Comment by Bjornskjald** [comment]
are you sure you ran `npm install -g miscord`?

**Comment by Nedihardt97** [comment]
![image](https://user-images.githubusercontent.com/25507769/41984624-1715fa84-79ff-11e8-9609-2c4f395f4242.png)

And thus was how I initially the program as well until it began to have the present issue

**Comment by Nedihardt97** [comment]
wait, that looks a bit different now

**Comment by Bjornskjald** [comment]
so you should be able now to run `miscord`

**Comment by Nedihardt97** [comment]
![image](https://user-images.githubusercontent.com/25507769/41984890-ce87c742-79ff-11e8-8f55-adfb8f11dafd.png)

Doing so gives more errors

**Comment by Nedihardt97** [comment]
wait, did the config move from Username/miscord to Username/AppData/Roaming/miscord ?

**Comment by Bjornskjald** [comment]
yup

**Comment by Bjornskjald** [comment]
I said, you were running a very outdated version

**Comment by Nedihardt97** [comment]
I presume I cannot just copy/paste the old config into the new directory

**Comment by Bjornskjald** [comment]
I think you can

**Comment by Bjornskjald** [comment]
if you rename "facebook" to "messenger"

**Comment by Nedihardt97** [comment]
![image](https://user-images.githubusercontent.com/25507769/41985575-ae77ee62-7a01-11e8-950c-57f441f520f5.png)

Results after pasting config, changing "facebook" -> "messenger", and using "miscord" command

**Comment by Bjornskjald** [comment]
oh, Miscord now needs create/use webhooks permissions

**Comment by Nedihardt97** [comment]
Awesome! It's successfully started!

**Comment by Bjornskjald** [comment]
is it working? if yes, then you can close the issue

**Comment by Nedihardt97** [comment]
Yes, just tested functionality as well, thanks for the help.
