### ISSUE TITLE
Commands not working due to wrong element and no shift (edit: channel commands due to missing `!`)

### ISSUE THREAD

**Issue by ajstewart** [Bjornskjald/miscord#258]
**Describe the bug**
I updated to v3.7.3 and found that no commands were working in the command channel. It was returning:

<img width="301" alt="screen shot 2018-06-29 at 3 23 10 pm" src="https://user-images.githubusercontent.com/3306161/42074622-5df14456-7bb0-11e8-8aea-4e932573acd1.png">

Looking at the following lines:

https://github.com/Bjornskjald/miscord/blob/8b854404a56f3adfcfe1838c90b5cbfccbd874f0/lib/handleCommand.js#L63-L65

This bug made sense as I think you meant to set the command to element [1] of the split array.

Following on from this, I then realised that doesn't a shift also need to be done on the array to remove the username? Then pass the new array string (using .join()) through? By this I mean I had to do the following to get it to work for me, which I expect can be written neater!:

```
  log.info('handleCommand', 'Command received!')
  message = message.trim()
  log.verbose('handleCommand', 'message: '+ message)
  var messagesplit = message.trim().split(' ')
  const command = messagesplit[1]
  messagesplit.shift()
  message = messagesplit.join(" ").trim()
  log.verbose('handleCommand', 'command: '+ command)
```

**To Reproduce**
Send any command string in the command channel from a release install.

**Expected behavior**
The commands should run.

**Specifications:**
miscord v3.7.3

**Comment by Bjornskjald** [comment]
but the mention is handled in lib/listeners/discord.js

**Comment by ajstewart** [comment]
So it should be! Apologies I completely missed that.

For what ever reason it looks like I have a `!` in the string:

```
verb discordListener message to send to handleCommand: <@!455909135658254346> help
verb discordListener client user id: <@455909135658254346>
info handleCommand Command received!
verb handleCommand message: <@!455909135658254346> help
```

So if I include the `!` in the replace string - then it works fine as expected.

```return handleCommand(message.content.replace(`<@!${config.discord.client.user.id}>`, ''))```

Have you seen the `!` before? Maybe it's something odd with my discord setup?

**Comment by Bjornskjald** [comment]
maybe I've missed it, I think I never tested it with channels, only with DMs
