### ISSUE TITLE
Status code 502

### ISSUE THREAD

**Issue by pyrah** [Bjornskjald/miscord#259]
Hello, 

I have many error like this  : 

WARN parseAndCheckLogin Got status code 502 - 1. attempt to retry in 412 milliseconds... 

In my logs, after this message, the application crash ! 

Do you have any idea for fix it ? 

thx

**Comment by Bjornskjald** [comment]
Unfortunately, it's a Facebook side error. There is nothing I can do about it.

**Comment by pyrah** [comment]
ok :+1: 

Thx for your (quick) answer.
