### ISSUE TITLE
Add support for logging in as page

### ISSUE THREAD

**Issue by Bjornskjald** [Bjornskjald/miscord#54]

**Comment by ShinNinth** [comment]
ive been working on something similar with the python sdk for discord and facebook to let a fb app post to pages shouldnt be too far off from doing the same with messenger ill dig into the api for this tonight and see if the calls are the same

**Comment by Bjornskjald** [comment]
Unfortunately, posting is not the same as messaging and there are probably different API calls.
Also, there would must to be another module just to perform these API calls, which won't be easy.

**Comment by ShinNinth** [comment]
After re-looking at schmavery's api ( i looked once a while ago and had forgot)  It is different then what i have been doing.  The API i have been using on Python can do both messenger and posts but its facebooks GraphAPI that has functions for both posting and dealing with messenger and allows you to use a page app.  There is a JavaScript GraphAPI sdk but i think you would be rewriting a large portion of your program if you moved to that though im not 100% sure.

**Comment by Bjornskjald** [comment]
I'm not very happy about having to deal with the official Facebook's API, because Facebook needs an API key and a lot of work including setting up an app, creating icon for it and sending it to review, so...
I'm afraid I would have to abandon this issue, unless Schmavery and others will find a way to get page messages once again (it worked some time ago).
Sending works, but receiving doesn't.

**Comment by ShinNinth** [comment]
I understand what you mean I have been jumping through the hoops to get this working for the project i have been hammering on the access tokens was a pain getting an app setup as a user wasnt bad it was getting a long lived token generated that was a pain in my neck.  Once i got that down It wasnt so bad though i havent tinkered with the chat portions quite yet just the portions for posting things to group pages.  Hopefully Schmavery and team pull through for you =/

**Comment by Bjornskjald** [comment]
Closing as it would need to implement official Facebook API.
