### ISSUE TITLE
Images do not show up on facebook lite on android

### ISSUE THREAD

**Issue by talormanda** [Bjornskjald/miscord#66]
Uploading images from discord, they do not show up on the Facebook Lite app on Android. They do show up on the full version of Facebook Messenger on Android. Not sure if there is anything that can be done due to the way images are attached. Just thought I would add my experiences.

**Comment by Bjornskjald** [comment]
The only viable solution I found is to add a swtich for reuploading pictures...

**Comment by Bjornskjald** [comment]
Well, they do show up, but it's not as beautiful as on regular Messenger

It's better than nothing though 🤷‍♂️
