### ISSUE TITLE
Error: No compatible version found: facebook-chat-ap1@'github:schmavery/facebook-chat-api'

### ISSUE THREAD

**Issue by HerbertDiesel** [Bjornskjald/miscord#78]
I keep getting this error when trying to install npm... I am on Linux and finding this process very confusing so far.

npm http GET https://registry.npmjs.org/emoji-strip
npm http GET https://registry.npmjs.org/facebook-chat-api
npm http GET https://registry.npmjs.org/remove-accents
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/discord.js
npm http 304 https://registry.npmjs.org/emoji-strip
npm http 304 https://registry.npmjs.org/remove-accents
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/facebook-chat-api
npm http 304 https://registry.npmjs.org/discord.js
npm ERR! Error: No compatible version found: facebook-chat-api@'github:schmavery/facebook-chat-api'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.1.8","0.1.9","0.1.10","0.1.11","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.2.8","0.2.9","0.2.10","0.2.11","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6","1.0.7","1.0.8","1.1.0","1.2.0","1.3.0","1.4.0"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/herbertdiesel/miscord
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/herbertdiesel/miscord/npm-debug.log
npm ERR! not ok code 0

**Comment by Bjornskjald** [comment]
have you got git installed?

**Comment by HerbertDiesel** [comment]
Yup I installed it previous to these errors.

**Comment by Bjornskjald** [comment]
Seems weird. Haven't ever got this error, I'll search and see what I can do

**Comment by Bjornskjald** [comment]
I see. Your Node.js version is too old. Did you installed it from the package repository for your distribution?

Try downloading it from here: https://nodejs.org/en/download/package-manager

**Comment by HerbertDiesel** [comment]
Thank you!

**Comment by HerbertDiesel** [comment]
I'll try that and let you know if it works once I get a chance to try it.
At work ATM

On Mar 8, 2018 10:32 AM, "Bjornskjald" <notifications@github.com> wrote:

Closed #78 <https://github.com/Bjornskjald/miscord/issues/78>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Bjornskjald/miscord/issues/78#event-1511650360>, or mute
the thread
