### ISSUE TITLE
Messages from Facebook come empty

### ISSUE THREAD

**Issue by Bjornskjald** [Bjornskjald/miscord#79]

**Comment by clhleung** [comment]
Strange I thought sending messages from Discord to Fb would come empty. I can receive FB messages in Discord just fine.

**Comment by Bjornskjald** [comment]
So for you it's the other way or everything works?

**Comment by clhleung** [comment]
Other way around. I can pull messages from FB and display it on Discord whenever someone types something new. The part that does not work for me is where I type messages on Discord in response to these FB chats and display it back to Fb. That part does not work for me.

**Comment by Bjornskjald** [comment]
Could you send screenshots?

**Comment by clhleung** [comment]
![dbce9be7-9084-469b-bd37-e21b5e218a07](https://user-images.githubusercontent.com/25076138/37141250-3ff30b24-2269-11e8-9bdc-7e980f846a2a.jpeg)
![ce5c549e-f6a1-4544-9dba-d6896f76b24f](https://user-images.githubusercontent.com/25076138/37141252-40e7aa76-2269-11e8-93c0-3124325a55c9.jpeg)

**Comment by clhleung** [comment]
The last 3 blue messages on fb gets sent, I type responses back but nothing appears back on fb

**Comment by wdbrs** [comment]
Some screenshots.  I did some troubleshooting as seen in the images.  At first it made it worse, but deleting the appstate.json file a second time and restarting it brought it back to how it started

![image 7](https://user-images.githubusercontent.com/30547415/37141341-b1a846c6-2282-11e8-8267-4317322e32ae.jpg)
![image 8](https://user-images.githubusercontent.com/30547415/37141342-b21024e4-2282-11e8-9315-7c2e37434ee9.jpg)

**Comment by Bjornskjald** [comment]
@wdbrs it seems as the messages are wrongly sent empty (the embed doesn't generate)

**Comment by clhleung** [comment]
Oh wait, I think I got it working. I figured out my problem. I was trying to send messages to Facebook from Discord using the Discord account that the message service was associated with, which does not work. But, if I add other Discord users and let them send messages to FB chats, it works. The same goes with the other way around, if I send messages on Fb using the fb account the miscord service is associated with, it does not appear on discord, unless I send messages on FB using a different account!

**Comment by Bjornskjald** [comment]
Oh, so for you the messages didn't come empty, they just didn't come at all.
I thought it was obvious not to use the same account, because it would get stuck in a loop and repeat itself everytime somebody sends a message

**Comment by clhleung** [comment]
Yeah, I didn't occur me to not use the same account, but I think that should be good note. After I tried switching to different Discord and FB accounts the service was not associated with, things started rolling downhill! Thanks.

**Comment by Bjornskjald** [comment]
@wdbrs Can you open index.js in a notepad (or better, the Windows 10 Code Writer) and add a       `console.dir(opts, {colors: true})` on 67th line?

It should look then like this:
![code](https://user-images.githubusercontent.com/26630168/37165047-f1ebd1ac-22fb-11e8-93bf-b72df334a7f7.png)

Then you can send an example message on Messenger and you should get the message object in your console, copy it and paste here (you can remove your userID and other private things)

**Comment by wdbrs** [comment]
The message I typed does apper under "body," but still shows empty"

_{ thread:
   { threadID: '     ',
     threadName: '     ',
     participantIDs: [ '     ', '     ' ],
     unreadCount: 1,
     messageCount: 25,
     timestamp: '1520543820935',
     isPinProtected: false,
     eventReminders: [],
     relatedPageThread: null,
     reactionsMuteMode: 'reactions_not_muted',
     mentionsMuteMode: 'mentions_not_muted',
     threadType: 'group',
     topEmojis: undefined,
     emoji: null,
     color: null,
     nicknames: { '     ': '     ' } },
  sender:
   { name: '     ',
     firstName: '     ',
     vanity: '     ',
     thumbSrc: '     ',
     profileUrl: '     ',
     gender: 2,
     type: 'user',
     isFriend: false,
     isBirthday: false },
  message:
   { type: 'message',
     senderID: '     ',
     body: 'Testing with console output',
     threadID: '     ',
     messageID: 'mid.$gAAcMgge1t4JoOL60h1iB3lwER_hO',
     attachments: [],
     mentions: {},
     timestamp: '1520543820935',
     isGroup: true } }_

**Comment by Bjornskjald** [comment]
Seems weird, I can get the same object passed through createEmbed and it doesn't return empty message... Did you try reinstalling? (you can backup config and appstate)

**Comment by wdbrs** [comment]
I just tried reinstalling, three times, the last time reinstalling git and node.js as well.  No improvement.  I can try it on a different computer tomorrow

**Comment by Bjornskjald** [comment]
@wdbrs Can you add another line?  
This time to `createEmbed.js`,
```javascript
console.dir(embed)
```
on 14th line so it looks like this:
![code](https://user-images.githubusercontent.com/26630168/37251941-677a0d34-2519-11e8-9659-75b5c69f3653.png)

**Comment by wdbrs** [comment]
Putting that code in and sending a message "testing" gives me this in Git BASH
```RichEmbed {
  title: undefined,
  description: 'testing',
  url: undefined,
  color: undefined,
  author:
   { name: ' ',
     icon_url: ' ',
     url: undefined },
  timestamp: undefined,
  fields: [],
  thumbnail: undefined,
  image: undefined,
  footer: undefined,
  file: undefined }
```
It still is blank though

**Comment by wdbrs** [comment]
I tried installing on a second system, running Windows 7.  Same exact problem, blank messages

**Comment by Bjornskjald** [comment]
@wdbrs I have literally no idea how could this be possible...
Are you sure you're not making any mistakes, like sending messages to yourself?

**Comment by Bjornskjald** [comment]
Okay, now it's happening to me too.
Moved to #110 as this thread is long and confusing.
