### ISSUE TITLE
Error when trying to launch the bot 

### ISSUE THREAD

**Issue by yfartel** [Bjornskjald/miscord#80]
After following the instruction to install the bot, all runs good but when I try to run "npm start" got this message ! 

Thanks.

[2018-03-08T13_13_19_766Z-debug.log](https://github.com/Bjornskjald/miscord/files/1793272/2018-03-08T13_13_19_766Z-debug.log)

**Comment by Bjornskjald** [comment]
I think your version of Node.js is too old. Can you try the newer version? (v8.x.x at least)

**Comment by yfartel** [comment]
Thanks for your help, working now !

**Comment by talormanda** [comment]
(discord permission on the bot needed adjusted)
