### ISSUE TITLE
Messenger message: mentions and usernames

### ISSUE THREAD

**Issue by mind12** [Bjornskjald/miscord#81]
- Discord profile username appears in messenger messages instead of the nickname. Nickname identifies the PoGO user exactly. I think I'm not the only one with this problem.

- Mention of a user or a channel appears with the ID in the messenger message. It's unreadable in messenger. Can it be converted?

Great tool anyway. Thank you for your hard work.

**Comment by Bjornskjald** [comment]
I'll search the Discord.js API for that, but I'm not sure if it's possible

**Comment by mind12** [comment]
I'll ask some bot developers about this. If I get any helpful answer I will post it here.
Thx

**Comment by Bjornskjald** [comment]
Nevermind, I found this.
[Message member](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=member)
[Message mentions](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=mentions)

**Comment by mind12** [comment]
Will those solve the problems?
May I ask you how can I update my bot if you do a commit?

**Comment by Bjornskjald** [comment]
If you downloaded .zip from GitHub, then backup your config file, delete `miscord-master` (or any other name if you renamed it) and move the config file back in this directory.
Then just `npm install` and it should be ready to work

**Comment by mind12** [comment]
Ok, so a complete re-install process will update it, thx.

**Comment by Bjornskjald** [comment]
@mind12 Done nickname checking, mentions will take a while...

**Comment by mind12** [comment]
Nice I saw the reference. Great job. I will update my bot soon. ;)
So many happy customers :)

**Comment by Toohpick** [comment]
You can use [message#cleanContent](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=cleanContent) instead of message#content for mentions.

**Comment by Bjornskjald** [comment]
...wow, didn't see that. Thanks!

**Comment by mind12** [comment]
Ok I guess I will wait a few more minutes before updating my bot :).

**Comment by Bjornskjald** [comment]
@mind12 OK, it's available now

**Comment by mind12** [comment]
Consider a donation link somewhere, our community is so happy about your work.
Thank you!

**Comment by Bjornskjald** [comment]
@mind12 It's up on the bottom of the README

**Comment by mind12** [comment]
Nice, I will share it to the community. Keep up the good work!

**Comment by Bjornskjald** [comment]
Thanks!
