### ISSUE TITLE
FR - Send messages from webhooks to messenger

### ISSUE THREAD

**Issue by emyb** [Bjornskjald/miscord#86]
It would be great if posts to webhook could be sent to facebook messenger

**Comment by Bjornskjald** [comment]
Could you edit your issue to match the issue template?  
Also, elaborate more. I don't know what are `posts to webhook`...  
Do you mean messages from page bots?

**Comment by Bjornskjald** [comment]
I'm not sure if that's possible.  
Does the webhook have its own separate channel, or it's on one of the Miscord channels?

**Comment by Bjornskjald** [comment]
Tested it. It should work
