### ISSUE TITLE
404 status code from FB

### ISSUE THREAD

**Issue by zeevalor** [Bjornskjald/miscord#89]
## Expected Behavior
When a message is posted on Discord, message should appear on FB messenger as well. 

## Actual Behavior
```
getUserInfo  Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
ERR! getUserInfo     at /Users/gc09292/ptc/miscord/miscord/node_modules/facebook-chat-api/utils.js:843:42
ERR! getUserInfo     at tryCatcher (/Users/gc09292/ptc/miscord/miscord/node_modules/bluebird/js/main/util.js:26:23)
ERR! getUserInfo     at Function.Promise.attempt.Promise.try (/Users/gc09292/ptc/miscord/miscord/node_modules/bluebird/js/main/method.js:31:24)
```

## Specifications

  - Platform: Mac
  - Version (can be found in package.json):  "version": "2.4.10",
  - Node.js version (`node -v`): v8.9.1

**Comment by Bjornskjald** [comment]
It's already a known issue, try restarting the bridge.
Related: https://github.com/Schmavery/facebook-chat-api/issues/576

**Comment by zeevalor** [comment]
I just started using the bridge and on first message from discord, I get the 404.  if I use the sample code from facebook-chat-api, I can use the account to echo back any messages to messenger. Could it be a config issue in the bridge that I have configured?

**Comment by Bjornskjald** [comment]
@zeevalor If you're sure you have mail/username and password correct, then it shouldn't be a config related issue.

**Comment by stanfear** [comment]
having the exact same issue running the latest docker image (4.5.2)
rebooting the docker doesn't change anything.

just tried with the classic install, same thing

I did make sure the login info were right

if you need the complete log, simply ask (although it is from module facebook-chat-api so you probably souldn't do much about it)

**Comment by Bjornskjald** [comment]
@stanfear does it say "getUserInfo" on the beginning?

**Comment by stanfear** [comment]
yeah

and returning to version 2.4.9 makes it work again ...

**Comment by stanfear** [comment]
ok really weird, 
after more test, it seems the error appears when talking in some other channel than a facebook synced channel
and the messages sent in the discord channel get to messenger, but messenger messages don't make it to Discord

**Comment by Bjornskjald** [comment]
could be related to #79

**Comment by Bjornskjald** [comment]
I'll check it, because it may be looking for nonexistent channels. Do you have any numbers in your channel's topic?

**Comment by Bjornskjald** [comment]
also is that channel on bot's category?

**Comment by stanfear** [comment]
from what I saw, issue #79 is the opposite of what happens to me,
I don't receive facebook messages in discord, but discord messages can be read in Messenger

**Comment by Bjornskjald** [comment]
but the later comments are saying about the same situation as yours

**Comment by stanfear** [comment]
the other thread is confusing me, I can't figure out who had what problems ...
and the one message where it kinda looks like my issue, the person was using the bot's account, I did my testing with a friend using another account

**Comment by Bjornskjald** [comment]
@stanfear see #110.

**Comment by Bjornskjald** [comment]
@zeevalor @stanfear Could you check if this issue happens on 2.6.2?

**Comment by stanfear** [comment]
@Bjornskjald works for me now.
Hope it won't stop working like last time !

**Comment by simeonlg** [comment]
I have had a similar issue when the bot was added to a new chat, but the message request had not been accepted yet

**Comment by Bjornskjald** [comment]
@simeonlg What do you mean by `similar issue`?

**Comment by Bjornskjald** [comment]
When you have a similar error, please copy it or screenshot and post it here

**Comment by Bjornskjald** [comment]
Doesn't really happen anymore (or nobody reported it).
